### ISSUE TITLE
Multiple games needing "@echo off"

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#101]
These games now have a user note for the CD change but dont have the echo off causing the prompt to display throughout the message.

American Girls Premiere, The (1997)
S.T.O.R.M. (1996)
Battle Isle 2220 - Shadow of the Emperor (1996)
Beyond Time (1997)
Connections (1995)
Where in Time is Carmen Sandiego (1997)
Front Page Sports - Trophy Bass 2 - Northern Lakes (1997)
Jeopardy TV and Movie Pack (1996)

**Comment by exoscoriae** [comment]
thanks. fixed.
