### ISSUE TITLE
Dark Seed II (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#102]
Just found a fix to an annoying item with this game that has bothered me for awhile. The beginning of every speech has stuttered, but with the below fix everything is working properly.

Quoted from a Vogons post:

"After the game has installed, there should be a file in the Windows directory called wavemix.ini. Inside that file is a bunch of settings that Dark Seed 2 seems to use for audio playback, and if you scroll down a bit you'll see that there are settings for specific sound cards, however, those do not appear to be being applied. What you'll want to do is alter the default settings to the ones for the SB16, so from the top of the file change WaveBlocks=3 to WaveBlocks=5, add WaveBlockLen=4096, and change SamplesPerSec=11 to SamplesPerSec=22. Stutter be gone!"

So it looks like the game isnt looking at the section for the SB16 and is applying all the settings at the top of the file. Change those default settings to the SB16 values and it works. I wonder if this would fix any other games that had a stutter? Problem is we never really tracked them as we assumed it was inherent to emulating win 3.1, definitely something to save in the toolbox though so we dont forget.

**Comment by Python-Exoproject** [comment]
Just confirmed this is relevant to other games with sound issues. I just fixed a long outstanding issue we had with Think-X, see #48 for more info

**Comment by exoscoriae** [comment]
Wow. Awesome :)

**Comment by exoscoriae** [comment]
fixed =)
