### ISSUE TITLE
Reminder for release

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#103]
This entry is a reminder to create an "eXoWin3x" LB entry to be the first entry in the Win3x platform with manual, setup.bat etc linked to it.

I also think the "Win3x" platform needs to be edited to have the "Parent" set to computers?

Will @TimberlAndRE-de installed games plugin work for win3x?

**Comment by exoscoriae** [comment]
Win3x was set to computer as parent, but didn't have root checked off. now it is set the same as eXoDOS

also added metadata wo the win3x category
changed display name to Windows 3.x
added original art for the platform

created game entry for eXoWin3x
added custom art for it
added project setup file as an additional application.

Once a manual exists that can be linked as well.

**Comment by TimberlAndRE-de** [comment]
@Python-Exoproject not yet
It looks for the path of the game containing exodos, so I need to add a second path for exowin3x

Can you tell me the correct folder structure of the current WIP? Then I'll add it to the plugin and send you a version for testing

**Comment by Python-Exoproject** [comment]
Something went wrong when you renamed the platform @exoscoriae, heres what im getting once I refreshed the images:

![old](https://user-images.githubusercontent.com/67406191/107121802-80f25a80-68e8-11eb-803f-8d51cacc7f8a.png)

Its most likely due to the renamed platform creating new folders with that platform name under Launchbox\Manuals, Launchbox\Images, Launchbox\Music, Launchbox\Games, etc. Not sure if you can just rename the old "Win3x" folders in those LB directories to the new name of "Windows 3x", but it might work.

You will also notice that its not showing the Windows 3X platform under the "Computers" subheading like "MS-DOS" is. If you untick "root" and tick "Computers (Category)" on the Parents tab of the "Windows 3x" platform that should move its location.

**Comment by Python-Exoproject** [comment]
@TimberlAndRE-de Heres the win3x path all the way to the conf of the first game, second conflict: \Launchbox\eXo\eXoWin3x\\!win3x\2ndConf

As you can see, pretty much the same as eXoDOS

**Comment by exoscoriae** [comment]
ok. I repointed the win3x platform to the original win3x folders. I then cleared my cache and verified it works for me.

@TimberlAndRE-de 
the differences are
eXoDOS = eXoWin3x
!dos = !win3x

the parent folders above are the same

**Comment by TimberlAndRE-de** [comment]
I posted the Plugin on the discord

Not sure if used on another function with case sensitive so I post it here:

I had to set the plugin to check for both ways, eXoWin3x and eXoWin3X since it's case sensitive 
The folder is named eXoWin3x but in the Windows 3x.xml it's always eXoWin3X in the paths

**Comment by TimberlAndRE-de** [comment]
@exoscoriae 
if not already done, please remember to create the autopopulated playlist "Installed eXoWin3x games"

**Comment by exoscoriae** [comment]
@TimberlAndRE-de 
Installed eXoWin3x Games.xml has been created
Most recent plugin has been copied into plugins folder
Fixed the xml by changing eXoWin3X to eXoWin3x
Currently running LB 11.6
Manually changing the install flag does work with the plug in., however running the games (either by using the config or launch bat ) does not have any effect on the install flag currently.

All other release reminders in this thread have been processed.

**Comment by exoscoriae** [comment]
plugin has been fixed
