### ISSUE TITLE
Microsoft Golf (1992) & Microsoft Golf 2.0 (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#2]
This is more cleanup than a bug, but when you increased the res and setup the in game windows you left the scorecard open in both games. For MS Golf 2 its just in the background and needs minimizing, in MS Golf 1 its only an issue if someone uses the exo player as the scorecard is saved open in the foreground overlaying everything else.

**Comment by exoscoriae** [comment]
done

**Comment by Python-Exoproject** [comment]
Tried to install MS Golf 2.0 and it wouldnt extract. added a pause to install.bat to see the error and got this:

![image](https://user-images.githubusercontent.com/67406191/106754780-7bdfa200-6681-11eb-8ab8-5813413c9a4e.png)

**Comment by exoscoriae** [comment]
interesting. I was able to extract it with winrar just fine. However I did notice that the file didn't have an extension yesterday. So I just renamed it with a zip and moved on. There must have been an issue.

Just tested the eXoDOS installer and it now works. good catch
