### ISSUE TITLE
More games needing a CD swap user note

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#22]
This list of games are all ECE so need a CTRL-F4 user note to inform how to swap CD's when requested.

Jewels II - The   Ultimate Challenge
Jonny Quest - The Real Adventures - Cover-Up at Roswell
Guignols de l'Info, Les - Le Cauchemar de PPD
Lighthouse - The Dark Being
Mirage
Police Quest SWAT
Secrets of the Luxor
Seymore Butts Interactive 2 - In Pursuit of Pleasure
Star Trek Omnipedia
Daedalus Encounter, The
Improv Presents, The - Don't Quit Your Day Job
Last Dynasty, The
Titanic - Adventure Out of Time

**Comment by exoscoriae** [comment]
all noted

**Comment by Python-Exoproject** [comment]
These games all need an "@echo off" added to avoid the prompt being displayed throughout the user note

**Comment by exoscoriae** [comment]
thanks for catching this. fixed.
