### ISSUE TITLE
Diva X - Ariana (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#25]
krc solved the no sound in large window issue we were having. Set cycles to 19000 and the problem goes away

**Comment by exoscoriae** [comment]
changed cycles

**Comment by Python-Exoproject** [comment]
You changed the cycles but left the user message in. The message is no longer needed now that the cycles fixed the issue.

**Comment by exoscoriae** [comment]
ther was no mention of the note in the initial bug report, so I didn't even bother scrolling down that far. fixed now.
