### ISSUE TITLE
Harpoon Classic '97 (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#32]
This is actually v1.60alpha and with the update in #31 bringing Harpoon Classic upto v1.63 is not only a duplicate copy of the same game but also now out of date compared to the other copy. I believe the copy here comes from the Win95 updated '97 release in which they just tossed an old copy of the original game onto the CD as a bone to those who still had win 3.1

**Comment by exoscoriae** [comment]
removed
