### ISSUE TITLE
Alternate Launcher

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#35]
We can rollout the alternate launcher to all win3x games with a few small edits to the current eXoDOS version of the alternate launcher.bat, Pixel Perfect works, not sure about if you want to bring over the CRT shader stuff.

**Comment by exoscoriae** [comment]
it won't work on vhd games. So they will have to be left empty, even though that will cause issues in the exotool

**Comment by Python-Exoproject** [comment]
Why do VHD's preclude alternate launcher? Using "Tower" as an example, it works. I know that any that use VHD because of the CD emulation issues wont work as ECE cant do that, but I didnt think VHD itself caused an issue as ECE can boot images. Even in the case of the CD issue games there arent many, why cant we just do what we did in exodos and add the alternate launcher to everything with the understanding that if it works, great, if not then stick with main launch? Its simpler for us as we dont need to decide where to put the launcher and where not to, its already how we do it in exodos, and its there if in the future we can get the game to work outside a VHD.

**Comment by exoscoriae** [comment]
because the VHD games also have to mount CD's, and as far as I can remember, ECE does not have IDE forwarding available in it. It's not a matter of if ECE can boot the vhd - it is a matter of passing the mounted cd-rom to the booted image and allowing the MSCDEX drivers to load properly. IIRC, only Daum and X can forward the IDE to the boot.

**Comment by exoscoriae** [comment]
I'm not opposed to adding it for all the games. I just think that the type of failure inherent to this is higher and more invasive.

A DOS game doesn't start, and you might be at a black screen. Windows games are much more dramatic and tend to royally shit the bed when they go wrong.

But it really shouldn't be hard to modified the old alternate launcher to work with these files.

**Comment by exoscoriae** [comment]
I have added an alternate launcher file to every games extras folder. The wording has been slightly modified to say:

echo Please note, all of the above options are experimental.
echo There is a chance your game won't run at all in this mode.

Now they need to be added to the front end. I believe the eXoTool is designed to ignore these for this platform however?

**Comment by Python-Exoproject** [comment]
Yeah, Ill have to ping Thorogin. Hes been busy with some big real life stuff recently but ill lodge the request

**Comment by Python-Exoproject** [comment]
Alt launcher is in
