### ISSUE TITLE
Journey to the Centre of the Earth (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#40]
Thought this one was fine then started chapter 3 at random. It says the first sentence on the page ok, but then the yellow highlighter for the text rapidly moves through the rest of the text and hits the end causing the voice over to stop.

The only solution we found was to use PCEM

**Comment by kcgen** [comment]
The audio tracks contain roughly 5 to 6-seconds of trailing silence, which might contribute to some kind of running deficit, as I noticed the CUE files doesn't have a the usual 150-frame (2-second) PREGAPs.

Looking at the pacing of the yellow-word highlight, especially on the first paragraph for the page (which corresponds to the start of of each track), the game expects the narrator to be ready-to-speak straight away.

To test, I stripped the tracks' pre-and-post "empty" PCM frames (essentially an "audio trim"), and zero'd the CUE so the tracks are packed back-to-back.

The packages was tested by **Smiling Spectre** and found to be acceptable:

> Checked your version. It works.
> Checked then european version on your setup. It works too.
> So image is right. Either Windows, or Dosbox itself is wrong.

Then the modified tracks could probably be package back into a modified BIN/CUE, with corrected CUE timings (if there's a strong desire to keep BIN/CUE format) Alternatively, it might be better just to deliver the original BIN/CUE for preservation sake, and then still package the ISO and FLAC tracks along-side it (as the working configuration).

**Comment by kcgen** [comment]
For future reference, the pre-and-post silence in a set of `.wav` files can be trimmed with this command:

```
parallel ffmpeg -i {} -af "silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp,areverse,silenceremove=start_periods=1:start_duration=1:start_threshold=-60dB:detection=peak,aformat=dblp,areverse" ../{} ::: *.wav
```

Requires GNU parallel and ffmpeg.

**Comment by SmilingSpectre** [comment]
Enforcing: there is **no need** to change anything in the game/disc itself. **Dosbox Staging** is the only requirement.

**Comment by kcgen** [comment]
@SmilingSpectre , thanks for running this first-order check (which I hadn't done, given in every other case we are equally affected).

**Comment by exoscoriae** [comment]
game is fixed by recent SVN commits.
