### ISSUE TITLE
Microsoft Bob (1995)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#44]
Stutter as per this vid:

https://cdn.discordapp.com/attachments/558636954992771073/695868375271735306/Microsoft_Bob-1.mp4

**Comment by Python-Exoproject** [comment]
Looks like this one is fixed with the WAVEMIX.INI fix as well. Use the same copy of this file found in issue #48 and overwrite one currently in msbob\windows. It might be worth saving this ini file with the roland driver stuff?

**Comment by exoscoriae** [comment]
such a great fix. thanks!
