### ISSUE TITLE
Alternate names and non standard characters.

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#45]
Not sure if there are any but this issue is just a note to add into LB and alternate names and to correct any non standard characters that cause issues with LB or your batch files and scripts.

**Comment by exoscoriae** [comment]
@Python-Exoproject 
do we have a list of the non standard characters that caused problems previously? iirc, it was with the auto downloader that the characters were problematic. And while I'm not opposed to fixing them just for the sake of avoiding future issues, for the forseeable future there are no plans for a "lite" version of eXoWin3x.

As far as alternate names go, this was added through the eXoTool. Do you know off hand if the win3x platform works with that feature?

**Comment by Python-Exoproject** [comment]
I am referring to that fact that is you search for "Barn" in LB and the game is called "Bàrn" it wouldnt show in results so an alt name for the game of "Barn" is needed to allow it to show up. Non standard characters also caused issues with some of the checks in exotool but I think Thorogin allowed for them.

As for the Alt Names table in exotool, im liaising with him to discuss

**Comment by exoscoriae** [comment]
@Python-Exoproject I know what you are referring to. However this was handled through the eXoTool. I did not go in and manually add all of those for eXoDOS.

**Comment by exoscoriae** [comment]
@TimberlAndRE-de has created the alternate names table. I just need to eXoTool to be able to read it and apply it at this point.

**Comment by exoscoriae** [comment]
alternate names have been applied to the xml.
