### ISSUE TITLE
THiNK-X (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#48]
There is a skipping effect in the music if you let it sit at the menu for a little. Same issue sometimes occurs during gameplay. This issue is with all dosbox versions.

**Comment by Python-Exoproject** [comment]
Tried the Dark Seed II fix on this game as its problem was sound stutter. It didnt have a "Wavemix.ini" in the windows folder but I copied in the one from DarkSeed II after I had modified it and now Think-X works 100%! Heres a copy of the file, put it in "think-x\windows"

[WAVEMIX.zip](https://github.com/exoscoriae/eXoWin3x/files/5922868/WAVEMIX.zip)

**Comment by exoscoriae** [comment]
fixed =)
