### ISSUE TITLE
GeoSafari (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#50]
I had made some recommended changes for this game but at the time you said no point as you were going to replace it with a deluxe version that integrates three geosafari games into one. Not sure if it ever happened though

**Comment by exoscoriae** [comment]
i believe I have the deluxe version in my stacks of games to be added.  however it wasn't for this release.

are there changes you would like pushed through for this game on this release?

**Comment by exoscoriae** [comment]
@Python-Exoproject

**Comment by Python-Exoproject** [comment]
Heres the old note I found:

Python28/02/2020
@eXo GeoSafari: Another boot game ive successfully tested with ECE. Just make sure to reduce cycles to avoid the sound spluttering when you move the mouse (30k seemed ok) and when installing skip the quicktime install as it doesnt work with the game, only the version of quicktime already installed in newwin archive does.

**Comment by Python-Exoproject** [comment]
You could also try that new WAVEMIX.INI solution found via Dark Seed II to see if it helps with any sound issues if needed.

**Comment by exoscoriae** [comment]
hmm. well, the game was already running in ECE. And I didn't have issues with quicktime.

The weirdest thing was the cd was in twice. once as an iso and once as a dumped folder. 

Using the iso with the CD folder causes it to look in the Z: for a file. But using the cd dump solves this.... what was the other game I just dealt with that displayed this behavior??

Anyways, this one runs fine for me currently. I'll let you test.

**Comment by Python-Exoproject** [comment]
Looks like I gave this the wrong title, it was meant to be relevant to GeoSafari (1997). @exoscoriae Shall I create a new issue or rename this one?

**Comment by exoscoriae** [comment]
renamed

**Comment by exoscoriae** [comment]
converted to ece, changed to openglnb.
game runs fine, no stuttering.
