### ISSUE TITLE
Mordor - The Depths of Dejenol (1995)

### ISSUE THREAD

**Issue by TimberlAndRE-de** [exoscoriae/eXoWin3x#52]
sharp_ey found the 

- [ ] manual

* source: [Discord](https://discord.com/channels/454359114601201666/625680023269015553/752863020870533212) / [old-games.ru](https://www.old-games.ru/game/download/916.html)
* file: GitHub\eXoWin3x\Manuals-Extras Discovery & Upgrade\Mordor - The Depths of Dejenol (1995)_manual.pdf
* quality: 1
* pages: 25
* notes: -

**Comment by exoscoriae** [comment]
added
