### ISSUE TITLE
Fury³ (1995)

### ISSUE THREAD

**Issue by bigjim161** [exoscoriae/eXoWin3x#77]
I found an add on "F!Zone for Fury 3"

https://www.mobygames.com/game/fzone-for-fury-3
"An add on to Fury³ for Windows, this adds additional levels to the game. Graphics and gameplay are identical in style to the original game, though new enemies have been added. In addition to the extra levels, a fairly advanced level editor is included for manipulating textures and creating your own levels."

Genre:   simulation
Developer:   WizardWorks Group, Inc.
Publisher:  WizardWorks Group, Inc.
Released:    1996
https://www.youtube.com/watch?v=KBmxr71aBDU

Added to the github folder eXoWin3x/Game Submission

**Comment by exoscoriae** [comment]
added
